### ISSUE TITLE
A possible Addon Translate...

### ISSUE THREAD

**Issue by AmodeusR** [Monacraft/AnkiDiscord#10]
Hello, I want to know if it's possible to translate the addon to another language. If so, I would like to translate it to portuguese so I and my colleagues can use it in our native tongue. Since it's a pretty simple addon, I reckon it wouldn't be much complicated.

Any possibility?

**Comment by Monacraft** [comment]
Dear @AmodeusR 

It's possible to translate the code quite easily, there would only be size lines that require changing.

Lines:

- 71 and 73 (translate for `"card(s) left"`)
- 98, 100, 103, 105 (translate the second arguement for the `update()` function each time)

If you ran this through in a forked version of the code you should have no problems sending the project to your friends to download while can run a portuguese version.

Apologies for the late response
