### ISSUE TITLE
Is it supposed to work on Linux?

### ISSUE THREAD

**Issue by michaelskyba** [Monacraft/AnkiDiscord#16]
I have tried using it on Ubuntu 20.04, but nothing changes inside Discord. If it _is_ supposed to work, I can provide more details to help solve this issue.

Also, this is my first time "opening an issue" on GitHub, so forgive me if I am doing something wrong here

**Comment by ardydo** [comment]
I think it is not? I have tried too and discord doesn't do anything whit it here too :/
